In [1]:
import numpy as np

In [2]:
myarr = np.array([1,12,3,4])   #creating an array using the list, we will pass a list as an argument 
myarr.sort()

In [3]:
#let's convert it into a 2d array
myarr = np.array([[1,2,3,4]])
myarr[0,1]
myarr.shape #determine the shape
myarr.dtype

dtype('int32')

In [4]:
myarr[0,1] = 7 #changing the element in an array at a certain position
myarr

array([[1, 7, 3, 4]])

In [5]:
#creation of array
#There are five ways to create an array in numpy:
# 1 way: using lists, tuple, sets
list1 = [1,2,3,4,45]
my_arr = np.array(list1)
tup = (1,2,3,6)
arra1 = np.array(tup)
tup
type(tup)

tuple

In [6]:
#way 2 
zero = np.zeros((3,3)) #here 3,3 are number of rows and columns respectively
zero
#using arange
rng = np.arange(10) #upto n-1 : 10-1 = 9
rng
#using linspace
lspace1 = np.linspace(1,4,4) #it will give me 4 elements from 1 to 4 spaced at an equal distance
lspace1
lspace = np.linspace(1,4,3) #it will give me 3 elements from 1 to 4 spaced at an equal distance
lspace
zero
one = np.ones((2,2))
one
lspace1

array([1., 2., 3., 4.])

In [7]:
#using empty function
emp = np.empty((3,3)) #it will create an array of 3*3 with garbage value
emp
# using empty_like function
emp_like = np.empty_like(arra1)  #it will create an empty array of size same as the existing one which you have put as an argument
emp_like

array([       2674,     2454016, -1418592256,  1912602624])

In [8]:
#using identity matrix
iden = np.identity((3)) #it will create an identity matrix or array of the order you will give. it must be a square matrix
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#reshaping of an array
arra1 = np.arange(15)
arra1
arra1 = arra1.reshape(3,5) #conversion will take place
arra1.ravel()
arra1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
arra1.shape = (5,3) #it will change the shape of the numpy array
arra1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
arr = np.asarray([2,3,4])
arr
ones = np.ones_like((5,4)) # it will create a copy as it takes an old array as an argument
ones
full = np.full((3,4),7) #3,4 are the rows and coulmns and 7 is the element which has to set in the array
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
ndlist = [[1,2,3],[4,5,6],[7,8,9]]
axis = np.array(ndlist)
axis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
axis.sum(axis=0) #axis 0 encounters all the columns and axis 1 deals with the rows

array([12, 15, 18])

In [13]:
axis.sum(axis=1)

array([ 6, 15, 24])

In [14]:
#transposing an array = row -> column and column -> row
axis.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
axis.flat

In [16]:
for element in axis:    #it will print all the lists
    print(element)

[1 2 3]
[4 5 6]
[7 8 9]


In [17]:
for item in axis.flat:  #it will all the element row wise
    print(item)

1
2
3
4
5
6
7
8
9


In [18]:
# attribute to check the dimensions of our array
axis.ndim

2

In [19]:
#total bytes occupied by the array
axis.nbytes

36

In [20]:
#size of the array
axis.size

9

In [21]:
# playing with one-d array
oned = np.array([9,3,4,15,6,10])
oned

array([ 9,  3,  4, 15,  6, 10])

In [22]:
oned.argmax() #give me the index of the highest or maximum value

3

In [23]:
oned.argmin() #give me the index of the lowest or minimum value

1

In [24]:
oned.argsort() #it will give me the indices, if we put the elements in the order we will get a sorted array

array([1, 2, 4, 0, 5, 3], dtype=int64)

In [25]:
#playing with 2-d array
axis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
axis.argmax()#count as row wise and then finds the index of the largest element which is nine in this case

8

In [27]:
axis.argmin() #count as row wise and then finds the index of the smallest element which is zero in this case

0

In [28]:
axis.argsort() #it tells the specific position of the elements in each list.

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [29]:
axis.argmax(axis=0) #tells us the indices of largest elements in every column if axis is 0

array([2, 2, 2], dtype=int64)

In [30]:
axis.argmax(axis=1) #tells us the indices of largest elements in every row if axis is 1

array([2, 2, 2], dtype=int64)

In [31]:
li = [[1,4,2],[9,3,5],[0,7,5]]
axis1 = np.array(li)
axis1

array([[1, 4, 2],
       [9, 3, 5],
       [0, 7, 5]])

In [32]:
axis1.argsort(axis=0) #self understoood

array([[2, 1, 0],
       [0, 0, 1],
       [1, 2, 2]], dtype=int64)

In [33]:
axis1.argsort(axis=1) #self understoood

array([[0, 2, 1],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [34]:
axis1.ravel()

array([1, 4, 2, 9, 3, 5, 0, 7, 5])

In [35]:
axis1.reshape((9,1))

array([[1],
       [4],
       [2],
       [9],
       [3],
       [5],
       [0],
       [7],
       [5]])

In [36]:
# Mathematical OPerations using Arrays
axis1

array([[1, 4, 2],
       [9, 3, 5],
       [0, 7, 5]])

In [37]:
axis2 = np.array([[2,3,4],
                  [1,6,0],
                  [-1,4,5]])
axis2

array([[ 2,  3,  4],
       [ 1,  6,  0],
       [-1,  4,  5]])

In [38]:
axis1+axis2 # same like adding two matrices in mathematics 

array([[ 3,  7,  6],
       [10,  9,  5],
       [-1, 11, 10]])

In [39]:
axis1*axis2 # element to element product

array([[ 2, 12,  8],
       [ 9, 18,  0],
       [ 0, 28, 25]])

In [40]:
np.sqrt(axis1) # calculate the square root of all the elements

array([[1.        , 2.        , 1.41421356],
       [3.        , 1.73205081, 2.23606798],
       [0.        , 2.64575131, 2.23606798]])

In [41]:
axis1.sum() # sum of all the elements in the array or matrix

36

In [42]:
axis2.sum() # sum of all the elements in the array or matrix

24

In [43]:
axis1.sum() + axis2.sum() 

60

In [44]:
axis1.max() #it will find the maximum element in the given array

9

In [45]:
axis2.max()

6

In [46]:
axis1.min()

0

In [47]:
axis2.min()

-1

In [48]:
np.where(axis1>3)  # tells us the indices of those elemenst which are greater than 3

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 0, 2, 1, 2], dtype=int64))

In [49]:
axis1

array([[1, 4, 2],
       [9, 3, 5],
       [0, 7, 5]])

In [50]:
np.count_nonzero(axis1) # tells us the total non-zero elements in the array

8

In [51]:
np.nonzero(axis1) #it will tell the indices of all the non zero elements present in the array

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [52]:
axis1[2,2] = 0

In [53]:
np.nonzero(axis1) # 2,2 has been vanished

(array([0, 0, 0, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1], dtype=int64))

In [54]:
# let's check Does Numpy takes less space
import sys
py_arr = [1,2,2,3,3]
np_arr = np.array(py_arr)

In [55]:
sys.getsizeof(1)*len(py_arr) 

140

In [56]:
np_arr.itemsize*np_arr.size

20

In [57]:
np_arr.nbytes

20

In [58]:
#conversion of numpy array to python list
axis1

array([[1, 4, 2],
       [9, 3, 5],
       [0, 7, 0]])

In [59]:
list1 = axis1.tolist() #if the array is multidimension it will give a nested list

In [60]:
list1

[[1, 4, 2], [9, 3, 5], [0, 7, 0]]

In [61]:
#axis1.dot()
#axis2*axis1
axis1.dot(axis2) #matrix multiplication
axis2.dot(axis1) # matrix multiplication

array([[29, 45, 19],
       [55, 22, 32],
       [35, 43, 18]])

In [66]:
axis3 = np.array([5,4,6,1,2])
axis3.partition(3) #still doubt full
axis3

array([1, 2, 4, 5, 6])

In [69]:
#joining two arrays
a = np.array([1,3,5])
b = np.array([2,4,6])
np.vstack((a,b)) #it will add the another array verticallly as a row

array([[1, 3, 5],
       [2, 4, 6]])

In [71]:
np.hstack((a,b)) #it will add the another array horizontally as columns

array([1, 3, 5, 2, 4, 6])

In [73]:
np.column_stack((a,b))  #it will first convert the exising arrays in in column and then join it horizontally

array([[1, 2],
       [3, 4],
       [5, 6]])